site_name: XP 词条分类项目 | 第一期
# site_url: https://csdiy.wiki/
site_author: 曦涟Elysielle
site_description: >-
  XP 词条分类项目 | 第一期

repo_name: xp-taxonomy
repo_url: https://github.com/FurinaLT/xp-taxonomy

theme:
  name: material
  language: zh
  logo: images/favicon.png
  favicon: images/favicon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - md_in_html
  - footnotes

plugins:
  - search

nav:
  - 前言: index.md
  - 分类方法历史版本:
    - V0.1 编号分类: 分类方法历史版本/V0.1 编号分类.md
    - V0.2 编号分类: 分类方法历史版本/V0.2 编号分类.md
  - 01 本体／生物结构:
    - 1生物种类:
      - 1普通种族:
        - 1人类:
          - 1扶她: 01 本体／生物结构/1生物种类/1普通种族/1人类/1扶她.md
          - 1人类: 01 本体／生物结构/1生物种类/1普通种族/1人类/index.md
        - 2人外:
          - 1A02.1 魔物娘: 01 本体／生物结构/1生物种类/1普通种族/2人外/1A02.1 魔物娘.md
          - 1A02.2 兽娘:
            - 1A02.21 猫娘: 01 本体／生物结构/1生物种类/1普通种族/2人外/1A02.2 兽娘/1A02.21 猫娘.md
            - 1A02.22 狼娘: 01 本体／生物结构/1生物种类/1普通种族/2人外/1A02.2 兽娘/1A02.22 狼娘.md
            - 1A02.23 狐娘: 01 本体／生物结构/1生物种类/1普通种族/2人外/1A02.2 兽娘/1A02.23 狐娘.md
            - 1A02.2 兽娘: 01 本体／生物结构/1生物种类/1普通种族/2人外/1A02.2 兽娘/index.md
          - 1A02.3 亚人: 01 本体／生物结构/1生物种类/1普通种族/2人外/1A02.3 亚人.md
          - 1A02.4 兽人: 01 本体／生物结构/1生物种类/1普通种族/2人外/1A02.4 兽人.md
          - 1A02.5 Furry: 01 本体／生物结构/1生物种类/1普通种族/2人外/1A02.5 Furry.md
          - 1A02.6 妖怪: 01 本体／生物结构/1生物种类/1普通种族/2人外/1A02.6 妖怪.md
          - 2人外: 01 本体／生物结构/1生物种类/1普通种族/2人外/index.md
      - 2神种族:
        - 1神明:
          - 1死神: 01 本体／生物结构/1生物种类/2神种族/1神明/1死神.md
          - 2半神: 01 本体／生物结构/1生物种类/2神种族/1神明/2半神.md
          - 1神明: 01 本体／生物结构/1生物种类/2神种族/1神明/index.md
        - 2天使:
          - 2堕天使: 01 本体／生物结构/1生物种类/2神种族/2天使/2堕天使.md
          - 2天使: 01 本体／生物结构/1生物种类/2神种族/2天使/index.md
      - 3类人种族:
        - 1精灵:
          - 1半精灵: 01 本体／生物结构/1生物种类/3类人种族/1精灵/1半精灵.md
          - 2黑暗精灵: 01 本体／生物结构/1生物种类/3类人种族/1精灵/2黑暗精灵.md
          - 1精灵: 01 本体／生物结构/1生物种类/3类人种族/1精灵/index.md
        - 2魔女(种族): 01 本体／生物结构/1生物种类/3类人种族/2魔女(种族).md
      - 4类兽种族:
        - 1猫又: 01 本体／生物结构/1生物种类/4类兽种族/1猫又.md
      - 5类爬行／虫种族:
        - 1虫族: 01 本体／生物结构/1生物种类/5类爬行／虫种族/1虫族.md
        - 2龙族: 01 本体／生物结构/1生物种类/5类爬行／虫种族/2龙族.md
      - 6魔鬼种族:
        - 1恶魔: 01 本体／生物结构/1生物种类/6魔鬼种族/1恶魔.md
        - 2鬼: 01 本体／生物结构/1生物种类/6魔鬼种族/2鬼.md
        - 3魅魔: 01 本体／生物结构/1生物种类/6魔鬼种族/3魅魔.md
        - 4魔族: 01 本体／生物结构/1生物种类/6魔鬼种族/4魔族.md
      - 7不死种族:
        - 1僵尸: 01 本体／生物结构/1生物种类/7不死种族/1僵尸.md
        - 2吸血鬼: 01 本体／生物结构/1生物种类/7不死种族/2吸血鬼.md
      - 8魔法物质／元素种族:
        - 1人偶(种族): 01 本体／生物结构/1生物种类/8魔法物质／元素种族/1人偶(种族).md
        - 2元素精灵: 01 本体／生物结构/1生物种类/8魔法物质／元素种族/2元素精灵.md
        - 3史莱姆: 01 本体／生物结构/1生物种类/8魔法物质／元素种族/3史莱姆.md
      - 9科幻种族:
        - 1克隆人: 01 本体／生物结构/1生物种类/9科幻种族/1克隆人.md
        - 2人格化兵器: 01 本体／生物结构/1生物种类/9科幻种族/2人格化兵器.md
        - 3机娘: 01 本体／生物结构/1生物种类/9科幻种族/3机娘.md
        - 4人造人: 01 本体／生物结构/1生物种类/9科幻种族/4人造人.md
      - y未特指种族:
        - 1萌拟人化: 01 本体／生物结构/1生物种类/y未特指种族/1萌拟人化.md
    - 2身体结构:
      - 1部位表现:
        - 1头部部位表现:
          - 口部部位表现:
            - 猫嘴: 01 本体／生物结构/2身体结构/1部位表现/1头部部位表现/口部部位表现/猫嘴.md
            - 虎牙: 01 本体／生物结构/2身体结构/1部位表现/1头部部位表现/口部部位表现/虎牙.md
            - 锯齿牙: 01 本体／生物结构/2身体结构/1部位表现/1头部部位表现/口部部位表现/锯齿牙.md
          - 面部部位表现:
            - PoRO脸: 01 本体／生物结构/2身体结构/1部位表现/1头部部位表现/面部部位表现/PoRO脸.md
            - 京都脸: 01 本体／生物结构/2身体结构/1部位表现/1头部部位表现/面部部位表现/京都脸.md
            - 包子脸: 01 本体／生物结构/2身体结构/1部位表现/1头部部位表现/面部部位表现/包子脸.md
        - 3上躯干部位表现:
          - 乳房部位表现:
            - 凸点: 01 本体／生物结构/2身体结构/1部位表现/3上躯干部位表现/乳房部位表现/凸点.md
            - 大小或形状:
              - 巨乳: 01 本体／生物结构/2身体结构/1部位表现/3上躯干部位表现/乳房部位表现/大小或形状/巨乳.md
              - 美乳: 01 本体／生物结构/2身体结构/1部位表现/3上躯干部位表现/乳房部位表现/大小或形状/美乳.md
              - 贫乳: 01 本体／生物结构/2身体结构/1部位表现/3上躯干部位表现/乳房部位表现/大小或形状/贫乳.md
            - 表面:
              - 下乳: 01 本体／生物结构/2身体结构/1部位表现/3上躯干部位表现/乳房部位表现/表面/下乳.md
              - 侧乳: 01 本体／生物结构/2身体结构/1部位表现/3上躯干部位表现/乳房部位表现/表面/侧乳.md
        - 4下躯干部位表现:
          - 腰部部位表现:
            - A4 腰: 01 本体／生物结构/2身体结构/1部位表现/4下躯干部位表现/腰部部位表现/A4 腰.md
            - 腰部部位表现: 01 本体／生物结构/2身体结构/1部位表现/4下躯干部位表现/腰部部位表现/index.md
            - 腰部翅膀: 01 本体／生物结构/2身体结构/1部位表现/4下躯干部位表现/腰部部位表现/腰部翅膀.md
          - 腹部部位表现:
            - 小肚腩: 01 本体／生物结构/2身体结构/1部位表现/4下躯干部位表现/腹部部位表现/小肚腩.md
          - 腿部部位表现:
            - 京都腿: 01 本体／生物结构/2身体结构/1部位表现/4下躯干部位表现/腿部部位表现/京都腿.md
            - 大长腿: 01 本体／生物结构/2身体结构/1部位表现/4下躯干部位表现/腿部部位表现/大长腿.md
            - 粗腿: 01 本体／生物结构/2身体结构/1部位表现/4下躯干部位表现/腿部部位表现/粗腿.md
          - 臀部部位表现:
            - 美臀: 01 本体／生物结构/2身体结构/1部位表现/4下躯干部位表现/臀部部位表现/美臀.md
            - 翘臀: 01 本体／生物结构/2身体结构/1部位表现/4下躯干部位表现/臀部部位表现/翘臀.md
        - 5生殖区部位表现:
          - 外阴部位表现:
            - 阴裂: 01 本体／生物结构/2身体结构/1部位表现/5生殖区部位表现/外阴部位表现/阴裂.md
          - 阴茎部位表现:
            - 巨根: 01 本体／生物结构/2身体结构/1部位表现/5生殖区部位表现/阴茎部位表现/巨根.md
            - 谜之凸起: 01 本体／生物结构/2身体结构/1部位表现/5生殖区部位表现/阴茎部位表现/谜之凸起.md
      - 2体积或形态变化:
        - 1头部基础变异:
          - 2耳部基础变异:
            - 尖耳朵: 01 本体／生物结构/2身体结构/2体积或形态变化/1头部基础变异/2耳部基础变异/尖耳朵.md
          - 5口部基础变异:
            - 长舌: 01 本体／生物结构/2身体结构/2体积或形态变化/1头部基础变异/5口部基础变异/长舌.md
        - 3上躯干基础变异:
          - 乳房基础变异:
            - 接地系超乳: 01 本体／生物结构/2身体结构/2体积或形态变化/3上躯干基础变异/乳房基础变异/接地系超乳.md
            - 超乳: 01 本体／生物结构/2身体结构/2体积或形态变化/3上躯干基础变异/乳房基础变异/超乳.md
        - 5生殖区基础变异:
          - 外阴基础变异:
            - 巨阴蒂: 01 本体／生物结构/2身体结构/2体积或形态变化/5生殖区基础变异/外阴基础变异/巨阴蒂.md
          - 睾丸基础变异:
            - 巨丸: 01 本体／生物结构/2身体结构/2体积或形态变化/5生殖区基础变异/睾丸基础变异/巨丸.md
            - 爆丸: 01 本体／生物结构/2身体结构/2体积或形态变化/5生殖区基础变异/睾丸基础变异/爆丸.md
            - 超丸: 01 本体／生物结构/2身体结构/2体积或形态变化/5生殖区基础变异/睾丸基础变异/超丸.md
          - 阴茎基础变异:
            - 爆根: 01 本体／生物结构/2身体结构/2体积或形态变化/5生殖区基础变异/阴茎基础变异/爆根.md
            - 超巨根: 01 本体／生物结构/2身体结构/2体积或形态变化/5生殖区基础变异/阴茎基础变异/超巨根.md
            - 超根: 01 本体／生物结构/2身体结构/2体积或形态变化/5生殖区基础变异/阴茎基础变异/超根.md
            - 马根: 01 本体／生物结构/2身体结构/2体积或形态变化/5生殖区基础变异/阴茎基础变异/马根.md
      - 3原部位替换:
        - 1头部原部位替换:
          - 2耳部原部位替换:
            - 耳部阴茎: 01 本体／生物结构/2身体结构/3原部位替换/1头部原部位替换/2耳部原部位替换/耳部阴茎.md
          - 5口部原部位替换:
            - 口部外阴: 01 本体／生物结构/2身体结构/3原部位替换/1头部原部位替换/5口部原部位替换/口部外阴.md
            - 舌头阴茎: 01 本体／生物结构/2身体结构/3原部位替换/1头部原部位替换/5口部原部位替换/舌头阴茎.md
          - 6头部阴茎化: 01 本体／生物结构/2身体结构/3原部位替换/1头部原部位替换/6头部阴茎化.md
        - 2颈部原部位替换:
          - 颈部阴茎: 01 本体／生物结构/2身体结构/3原部位替换/2颈部原部位替换/颈部阴茎.md
        - 3上躯干原部位替换:
          - 乳房原部位替换:
            - 乳头阴茎: 01 本体／生物结构/2身体结构/3原部位替换/3上躯干原部位替换/乳房原部位替换/乳头阴茎.md
        - 7上肢原部位替换:
          - 手指阴茎: 01 本体／生物结构/2身体结构/3原部位替换/7上肢原部位替换/手指阴茎.md
          - 手部阴茎: 01 本体／生物结构/2身体结构/3原部位替换/7上肢原部位替换/手部阴茎.md
        - 8下肢原部位替换:
          - 足部阴茎: 01 本体／生物结构/2身体结构/3原部位替换/8下肢原部位替换/足部阴茎.md
        - x其他特指的原部位替换:
          - 1B2Y.1 阴茎化: 01 本体／生物结构/2身体结构/3原部位替换/x其他特指的原部位替换/1B2Y.1 阴茎化.md
          - 1完全阴茎化: 01 本体／生物结构/2身体结构/3原部位替换/x其他特指的原部位替换/1完全阴茎化.md
          - 2躯体阴茎化: 01 本体／生物结构/2身体结构/3原部位替换/x其他特指的原部位替换/2躯体阴茎化.md
          - 3融合阴茎化: 01 本体／生物结构/2身体结构/3原部位替换/x其他特指的原部位替换/3融合阴茎化.md
          - 尾巴阴茎: 01 本体／生物结构/2身体结构/3原部位替换/x其他特指的原部位替换/尾巴阴茎.md
      - 4延伸组织:
        - 1头部延伸组织:
          - 1头顶延伸组织:
            - 头部翅膀: 01 本体／生物结构/2身体结构/4延伸组织/1头部延伸组织/1头顶延伸组织/头部翅膀.md
            - 角:
              - 角: 01 本体／生物结构/2身体结构/4延伸组织/1头部延伸组织/1头顶延伸组织/角/index.md
              - 双角: 01 本体／生物结构/2身体结构/4延伸组织/1头部延伸组织/1头顶延伸组织/角/双角.md
            - 触手: 01 本体／生物结构/2身体结构/4延伸组织/1头部延伸组织/1头顶延伸组织/触手.md
            - 触角: 01 本体／生物结构/2身体结构/4延伸组织/1头部延伸组织/1头顶延伸组织/触角.md
          - 2耳部延伸组织:
            - 兽耳:
              - 兽耳: 01 本体／生物结构/2身体结构/4延伸组织/1头部延伸组织/2耳部延伸组织/兽耳/index.md
              - 兔耳: 01 本体／生物结构/2身体结构/4延伸组织/1头部延伸组织/2耳部延伸组织/兽耳/兔耳.md
              - 犬耳: 01 本体／生物结构/2身体结构/4延伸组织/1头部延伸组织/2耳部延伸组织/兽耳/犬耳.md
              - 猫耳: 01 本体／生物结构/2身体结构/4延伸组织/1头部延伸组织/2耳部延伸组织/兽耳/猫耳.md
        - 4下躯干延伸组织:
          - 腰部延伸组织:
            - 腰部延伸组织: 01 本体／生物结构/2身体结构/4延伸组织/4下躯干延伸组织/腰部延伸组织/index.md
            - 腰部翅膀: 01 本体／生物结构/2身体结构/4延伸组织/4下躯干延伸组织/腰部延伸组织/腰部翅膀.md
          - 骶部延伸组织:
            - 尾巴:
              - 尾巴: 01 本体／生物结构/2身体结构/4延伸组织/4下躯干延伸组织/骶部延伸组织/尾巴/index.md
              - 心型尾巴: 01 本体／生物结构/2身体结构/4延伸组织/4下躯干延伸组织/骶部延伸组织/尾巴/心型尾巴.md
              - 箭头尾巴: 01 本体／生物结构/2身体结构/4延伸组织/4下躯干延伸组织/骶部延伸组织/尾巴/箭头尾巴.md
        - x其他特指延伸组织:
          - 翅膀:
            - 翅膀: 01 本体／生物结构/2身体结构/4延伸组织/x其他特指延伸组织/翅膀/index.md
            - 羽翼型翅膀: 01 本体／生物结构/2身体结构/4延伸组织/x其他特指延伸组织/翅膀/羽翼型翅膀.md
            - 蝉翼型翅膀: 01 本体／生物结构/2身体结构/4延伸组织/x其他特指延伸组织/翅膀/蝉翼型翅膀.md
            - 蝠翼型翅膀: 01 本体／生物结构/2身体结构/4延伸组织/x其他特指延伸组织/翅膀/蝠翼型翅膀.md
          - 鳍: 01 本体／生物结构/2身体结构/4延伸组织/x其他特指延伸组织/鳍.md
      - 4非原部位替换:
        - 1头部非原部位替换:
          - 2在耳部的非原部位替换:
            - 2翅膀型耳朵: 01 本体／生物结构/2身体结构/4非原部位替换/1头部非原部位替换/2在耳部的非原部位替换/2翅膀型耳朵.md
            - 3鳍型耳朵: 01 本体／生物结构/2身体结构/4非原部位替换/1头部非原部位替换/2在耳部的非原部位替换/3鳍型耳朵.md
        - 7上肢非原部位替换:
          - 翅膀型上肢: 01 本体／生物结构/2身体结构/4非原部位替换/7上肢非原部位替换/翅膀型上肢.md
      - 5增量变异:
        - 1头部增量变异:
          - 眼部增量变异:
            - 三只眼: 01 本体／生物结构/2身体结构/5增量变异/1头部增量变异/眼部增量变异/三只眼.md
          - 耳部增量变异:
            - 四耳: 01 本体／生物结构/2身体结构/5增量变异/1头部增量变异/耳部增量变异/四耳.md
        - 5生殖区增量变异:
          - 阴茎增量变异:
            - 复根: 01 本体／生物结构/2身体结构/5增量变异/5生殖区增量变异/阴茎增量变异/复根.md
        - 9翅膀部增量变异:
          - 六翼: 01 本体／生物结构/2身体结构/5增量变异/9翅膀部增量变异/六翼.md
          - 四翼: 01 本体／生物结构/2身体结构/5增量变异/9翅膀部增量变异/四翼.md
        - B尾巴增量变异:
          - B尾巴增量变异: 01 本体／生物结构/2身体结构/5增量变异/B尾巴增量变异/index.md
          - 九尾: 01 本体／生物结构/2身体结构/5增量变异/B尾巴增量变异/九尾.md
          - 双尾: 01 本体／生物结构/2身体结构/5增量变异/B尾巴增量变异/双尾.md
      - 6减量变异:
        - 1头部减量变异:
          - 眼部减量变异:
            - 单眼: 01 本体／生物结构/2身体结构/6减量变异/1头部减量变异/眼部减量变异/单眼.md
        - 9翅膀部减量变异:
          - 片翼: 01 本体／生物结构/2身体结构/6减量变异/9翅膀部减量变异/片翼.md
        - A角部减量变异:
          - 独角: 01 本体／生物结构/2身体结构/6减量变异/A角部减量变异/独角.md
    - 01 本体／生物结构: 01 本体／生物结构/index.md
  - Y 附属词:
    - XA 部位:
      - XA01 头颈部:
        - XA01.01 头部: Y 附属词/XA 部位/XA01 头颈部/XA01.01 头部.md
        - XA01.02 颈: Y 附属词/XA 部位/XA01 头颈部/XA01.02 颈.md
        - XA01.03 面: Y 附属词/XA 部位/XA01 头颈部/XA01.03 面.md
        - XA01.04 口部: Y 附属词/XA 部位/XA01 头颈部/XA01.04 口部.md
        - XA01.05 口周: Y 附属词/XA 部位/XA01 头颈部/XA01.05 口周.md
        - XA01.06 牙齿: Y 附属词/XA 部位/XA01 头颈部/XA01.06 牙齿.md
        - XA01.07 鼻: Y 附属词/XA 部位/XA01 头颈部/XA01.07 鼻.md
        - XA01.08 眼部: Y 附属词/XA 部位/XA01 头颈部/XA01.08 眼部.md
        - XA01.09 眉: Y 附属词/XA 部位/XA01 头颈部/XA01.09 眉.md
        - XA01.0A 眶: Y 附属词/XA 部位/XA01 头颈部/XA01.0A 眶.md
        - XA01.0B 瞳孔: Y 附属词/XA 部位/XA01 头颈部/XA01.0B 瞳孔.md
      - XA01 头颈部: Y 附属词/XA 部位/XA01 头颈部.md
      - XA02 躯干:
        - XA02.01 上躯干: Y 附属词/XA 部位/XA02 躯干/XA02.01 上躯干.md
        - XA02.02 下躯干: Y 附属词/XA 部位/XA02 躯干/XA02.02 下躯干.md
        - XA02.03 背: Y 附属词/XA 部位/XA02 躯干/XA02.03 背.md
        - XA02.04 肛门生殖器区: Y 附属词/XA 部位/XA02 躯干/XA02.04 肛门生殖器区.md
        - XA02.05 乳房: Y 附属词/XA 部位/XA02 躯干/XA02.05 乳房.md
        - XA02.06 乳头: Y 附属词/XA 部位/XA02 躯干/XA02.06 乳头.md
        - XA02.07 乳房下曲: Y 附属词/XA 部位/XA02 躯干/XA02.07 乳房下曲.md
        - XA02.08 输乳管: Y 附属词/XA 部位/XA02 躯干/XA02.08 输乳管.md
        - XA02.0A 腹部: Y 附属词/XA 部位/XA02 躯干/XA02.0A 腹部.md
        - XA02.0B 脐: Y 附属词/XA 部位/XA02 躯干/XA02.0B 脐.md
        - XA02.0C 侧腰区: Y 附属词/XA 部位/XA02 躯干/XA02.0C 侧腰区.md
        - XA02.0D 生殖区:
          - XA02.D.01 外阴: Y 附属词/XA 部位/XA02 躯干/XA02.0D 生殖区/XA02.D.01 外阴.md
          - XA02.D.02 阴唇: Y 附属词/XA 部位/XA02 躯干/XA02.0D 生殖区/XA02.D.02 阴唇.md
          - XA02.D.03 阴蒂: Y 附属词/XA 部位/XA02 躯干/XA02.0D 生殖区/XA02.D.03 阴蒂.md
          - XA02.D.04 阴囊: Y 附属词/XA 部位/XA02 躯干/XA02.0D 生殖区/XA02.D.04 阴囊.md
          - XA02.D.05 阴茎: Y 附属词/XA 部位/XA02 躯干/XA02.0D 生殖区/XA02.D.05 阴茎.md
          - XA02.D.06 龟头: Y 附属词/XA 部位/XA02 躯干/XA02.0D 生殖区/XA02.D.06 龟头.md
          - XA02.D.07 阴茎冠状沟: Y 附属词/XA 部位/XA02 躯干/XA02.0D 生殖区/XA02.D.07 阴茎冠状沟.md
        - XA02.0D 生殖区: Y 附属词/XA 部位/XA02 躯干/XA02.0D 生殖区.md
        - XA02.0E 肛门: Y 附属词/XA 部位/XA02 躯干/XA02.0E 肛门.md
        - XA02.0F 股沟: Y 附属词/XA 部位/XA02 躯干/XA02.0F 股沟.md
        - XA02.0G 会阴: Y 附属词/XA 部位/XA02 躯干/XA02.0G 会阴.md
        - XA02.0H 阴阜: Y 附属词/XA 部位/XA02 躯干/XA02.0H 阴阜.md
      - XA02 躯干: Y 附属词/XA 部位/XA02 躯干.md
      - XA03 四肢:
        - XA03.01 肩: Y 附属词/XA 部位/XA03 四肢/XA03.01 肩.md
        - XA03.02 腋: Y 附属词/XA 部位/XA03 四肢/XA03.02 腋.md
        - XA03.03 上臂: Y 附属词/XA 部位/XA03 四肢/XA03.03 上臂.md
        - XA03.04 肘: Y 附属词/XA 部位/XA03 四肢/XA03.04 肘.md
        - XA03.05 前臂: Y 附属词/XA 部位/XA03 四肢/XA03.05 前臂.md
        - XA03.06 腕: Y 附属词/XA 部位/XA03 四肢/XA03.06 腕.md
        - XA03.07 手: Y 附属词/XA 部位/XA03 四肢/XA03.07 手.md
        - XA03.08 臀部: Y 附属词/XA 部位/XA03 四肢/XA03.08 臀部.md
        - XA03.09 大腿: Y 附属词/XA 部位/XA03 四肢/XA03.09 大腿.md
        - XA03.0A 膝: Y 附属词/XA 部位/XA03 四肢/XA03.0A 膝.md
        - XA03.0B 小腿: Y 附属词/XA 部位/XA03 四肢/XA03.0B 小腿.md
        - XA03.0C 踝: Y 附属词/XA 部位/XA03 四肢/XA03.0C 踝.md
        - XA03.0D 足: Y 附属词/XA 部位/XA03 四肢/XA03.0D 足.md
        - XA03.0E 手指: Y 附属词/XA 部位/XA03 四肢/XA03.0E 手指.md
        - XA03.0F 趾: Y 附属词/XA 部位/XA03 四肢/XA03.0F 趾.md
      - XA03 四肢: Y 附属词/XA 部位/XA03 四肢.md
    - XB 表现:
      - XB01 装饰型: Y 附属词/XB 表现/XB01 装饰型.md
      - XB02 功能型: Y 附属词/XB 表现/XB02 功能型.md
    - XC 变化:
      - XC01 变化型变异: Y 附属词/XC 变化/XC01 变化型变异.md
      - XC02 生长型变异: Y 附属词/XC 变化/XC02 生长型变异.md
    - XD 拓扑学量表值:
      - XD01 关系:
        - XD01.01 前侧: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.01 前侧.md
        - XD01.02 后侧: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.02 后侧.md
        - XD01.03 中间: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.03 中间.md
        - XD01.04 侧面: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.04 侧面.md
        - XD01.05 上的: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.05 上的.md
        - XD01.06 下侧: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.06 下侧.md
        - XD01.07 腹侧: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.07 腹侧.md
        - XD01.08 背侧: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.08 背侧.md
        - XD01.09 近端: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.09 近端.md
        - XD01.0A 远端: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.0A 远端.md
        - XD01.0B 同侧: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.0B 同侧.md
        - XD01.0C 对侧: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.0C 对侧.md
        - XD01.0D 外侧: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.0D 外侧.md
        - XD01.0E 内侧: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.0E 内侧.md
        - XD01.0F 表浅: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.0F 表浅.md
        - XD01.0G 深部: Y 附属词/XD 拓扑学量表值/XD01 关系/XD01.0G 深部.md
      - XD01 关系: Y 附属词/XD 拓扑学量表值/XD01 关系.md
      - XD02 侧性:
        - XD02.01 双侧: Y 附属词/XD 拓扑学量表值/XD02 侧性/XD02.01 双侧.md
        - XD02.02 左侧: Y 附属词/XD 拓扑学量表值/XD02 侧性/XD02.02 左侧.md
        - XD02.03 右侧: Y 附属词/XD 拓扑学量表值/XD02 侧性/XD02.03 右侧.md
        - XD02.04 未特指的单侧: Y 附属词/XD 拓扑学量表值/XD02 侧性/XD02.04 未特指的单侧.md
      - XD02 侧性: Y 附属词/XD 拓扑学量表值/XD02 侧性.md
  - Z 收录进度 自用: Z 收录进度 自用.md
  - Z 缓存区 自用: Z 缓存区 自用.md
  - Z+ 增删日志: Z+ 增删日志.md
  - Z+ 暂存区: Z+ 暂存区.md